<?php
/**
 * @file
 * Drupal needs this blank file.
 */

/**
 * Implements hook_wysiwyg_editor_settings_alter
 */
function sitenow_wysiwyg_wysiwyg_editor_settings_alter(&$settings, $context) {
  //Check if the editor is ckeditor
  if ($context['profile']->editor == 'ckeditor') {
        //Enable the spell checker by default
    $settings['scayt_autoStartup'] = true;
    
    // Include custom css files
    $module_location = $GLOBALS['base_path'] . drupal_get_path('module', 'sitenow_wysiwyg');
    $settings['contentsCss'][] = $module_location . '/css/wysiwyg.css';
  }
}